site_name: roboware-neo.universe docs
site_url: https://github.com/hakoroboken/roboware-neo.universe
repo_url: https://github.com/hakoroboken/roboware-neo.universe
edit_uri: https://github.com/hakoroboken/roboware-neo.universe
docs_dir: docs
copyright: Copyright &copy; 2024 Hakoroboken

theme:
  name: material
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  favicon: assets/images/logo2.png
  icon:
    logo: material/file-document

  language: ja
  palette:
    - scheme: default
      primary: white
    

extra:
  font:
    text: Roboto
    code: Roboto Mono
  version:
    provider: mike

extra_css:
  - https://use.fontawesome.com/releases/v5.15.4/css/all.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
  - awesome-pages
  - exclude:
      regex:
        - ^(?!(.*/)?assets/).*\.(?!(.*\.)?md|(.*\.)?svg|(.*\.)?png|(.*\.)?jpg).*$
        - ^(.*/)?[^.]*$
  - macros
  - same-dir
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
  - mdx_math
  - mdx_truly_sane_lists:
      nested_indent: 2
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
      format: svg
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
      toc_depth: 3
  - pymdownx.tasklist:
      custom_checkbox: true
