/**:
  ros__parameters:

    noise.transoform.strength: 1.0
    noise.transoform.sd: 0.2
    noise.rotation.strength: 1.0
    noise.rotation_tr.strength: 1.0
    noise.rotation.sd: 0.2

    frameid.map: map
    frameid.base_link: base_link