name: scenario simulation

on:
  pull_request:
    branches: [ main ]

jobs:
  scenario_simulation:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        rosdistro:
          - humble

    runs-on: ubuntu-latest

    container:
      image: ros:${{ matrix.rosdistro }}-ros-base

    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: sersoft-gmbh/setup-gh-cli-action@v2
        with:
          version: stable

      - name: Mark directory as safe
        run: git config --global --add safe.directory /__w/roboware-neo.universe/roboware-neo.universe
        shell: bash

      - name: Install dependencies
        run: |
          rosdep update && 
          apt-get update && 
          rosdep install --from-path . -i -y --rosdistro ${{ matrix.rosdistro }} --skip-keys=OpenCV --skip-keys=PCL
        shell: bash

      - name: Install diagnostic-updater
        run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater
        shell: bash

      - name: Build tests
        id: build_test
        run: |
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh && 
          colcon build
        continue-on-error: true
        shell: bash

      - name: build_test command success
        if: steps.build_test.outcome == 'success'
        run: echo "result - success"
        shell: bash

      - name: build_test command failure
        if: steps.build_test.outcome == 'failure'
        run: echo "result - failure" && exit 1
        shell: bash

      - name: Scenario Simulation -> Simple
        run: |
          source /opt/ros/humble/local_setup.bash && 
          source install/local_setup.bash && 
          ros2 launch roboware_neo_launch scenario.simple_sim.launch
        continue-on-error: true
        shell: bash

      - name: Result output
        run: |
          python3 ./tools/ss_action.py comment simple_scenario
        shell: bash

      - name: Scenario Simulation -> Avoidance
        run: |
          source /opt/ros/humble/local_setup.bash && 
          source install/local_setup.bash && 
          ros2 launch roboware_neo_launch scenario.avoidance.launch
        continue-on-error: true
        shell: bash

      - name: Result output
        run: |
          python3 ./tools/ss_action.py comment simple_avoidance
        shell: bash

      - name: Scenario Simulation -> rotation
        run: |
          source /opt/ros/humble/local_setup.bash && 
          source install/local_setup.bash && 
          ros2 launch roboware_neo_launch scenario.rotation.launch
        continue-on-error: true
        shell: bash

      - name: Result output
        run: |
          python3 ./tools/ss_action.py comment simple_rotation
        shell: bash

      - name: Comment to PR
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "${PR_NUMBER}" -F ./comment
        shell: bash